#Launch with PR only
#trigger:
#  branches:
#    include:
#      - feature/*
pr:
  - feature/*
  
pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: main
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-Psmoke-tests'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: junit
  dependsOn: main
  condition: succeeded('main')
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      options: '-Plegacy-integration-tests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

- job: component
  dependsOn: main
  condition: succeeded('main')
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      options: '-Pcomponent-tests'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

#branch02 commit 
